mircoservices:
  endpoints:
    college: http://microB-college/college/
    address: http://microC-address/address/
    student: http://microA-student/student/
    

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: ${spring.application.name}

common:
  text: v1-common-text
