server:
  port: 0 #8523
  servlet:
    context-path: /address

#putting  common properties on github reading from cloud config server
#https://github.com/coddinginjava/cloud-config-server-ymls/tree/master
#so removing the tree mircoservices & eureka

#mircoservices:
#  endpoints:
#    college: http://microB-college/college/
#    address: http://microC-address/address/
#    student: http://microA-student/student/


spring:
  application:
    name: microC-address
#  zipkin:
#    enabled: false

sample:
  text: local-yml

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
##  instance:
##    hostname: ${spring.application.name}